/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.task;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringUtilsTest {

    @Test
    void testIsPositiveNumber() {

        StringUtils stringUtils = new StringUtils();
        assertTrue(stringUtils.isPositiveNumber("2"));
        assertFalse(stringUtils.isPositiveNumber("-1"));
        assertFalse(stringUtils.isPositiveNumber("abc"));
    }
}
