/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.task;

import org.apache.commons.lang3.math.NumberUtils;

public class StringUtils {

    boolean isPositiveNumber(String str) {

        if (!NumberUtils.isCreatable(str)) {
            return false;
        }
        int number = NumberUtils.toInt(str);
        return number > 0;
    }
}
